/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.imobi.report;

import br.com.imobi.app.Main;
import br.com.imobi.model.Imovel;
import java.io.FileNotFoundException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.TypedQuery;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author dglsw
 */
public class ReportJDialog extends javax.swing.JDialog {

    /**
     * Creates new form ReportJDialog
     */
    public ReportJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupDisponivel = new javax.swing.ButtonGroup();
        btnGroupFavorito = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rdDisponivelSim = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        rdDisponivelNao = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rdFavoritosSim = new javax.swing.JRadioButton();
        rdFavoritosNao = new javax.swing.JRadioButton();
        rdDisponivelTodos = new javax.swing.JRadioButton();
        rdFavoritosTodos = new javax.swing.JRadioButton();
        btnGerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Imóveis"));

        btnGroupDisponivel.add(rdDisponivelSim);
        rdDisponivelSim.setSelected(true);
        rdDisponivelSim.setText("Sim");
        rdDisponivelSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdDisponivelSimActionPerformed(evt);
            }
        });

        jLabel1.setText("Disponível");

        btnGroupDisponivel.add(rdDisponivelNao);
        rdDisponivelNao.setText("Não");
        rdDisponivelNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdDisponivelNaoActionPerformed(evt);
            }
        });

        jLabel2.setText("Favorito");

        btnGroupFavorito.add(rdFavoritosSim);
        rdFavoritosSim.setSelected(true);
        rdFavoritosSim.setText("Sim");
        rdFavoritosSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFavoritosSimActionPerformed(evt);
            }
        });

        btnGroupFavorito.add(rdFavoritosNao);
        rdFavoritosNao.setText("Não");
        rdFavoritosNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFavoritosNaoActionPerformed(evt);
            }
        });

        btnGroupDisponivel.add(rdDisponivelTodos);
        rdDisponivelTodos.setText("Todos");
        rdDisponivelTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdDisponivelTodosActionPerformed(evt);
            }
        });

        btnGroupFavorito.add(rdFavoritosTodos);
        rdFavoritosTodos.setText("Todos");
        rdFavoritosTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFavoritosTodosActionPerformed(evt);
            }
        });

        btnGerar.setText("Gerar relatório");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdDisponivelSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdDisponivelNao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdDisponivelTodos))
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdFavoritosSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdFavoritosNao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdFavoritosTodos)))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdDisponivelSim)
                    .addComponent(rdDisponivelNao)
                    .addComponent(rdDisponivelTodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdFavoritosSim)
                    .addComponent(rdFavoritosNao)
                    .addComponent(rdFavoritosTodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGerar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdDisponivelSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdDisponivelSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdDisponivelSimActionPerformed

    private void rdDisponivelNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdDisponivelNaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdDisponivelNaoActionPerformed

    private void rdFavoritosSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFavoritosSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdFavoritosSimActionPerformed

    private void rdFavoritosNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFavoritosNaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdFavoritosNaoActionPerformed

    private void rdDisponivelTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdDisponivelTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdDisponivelTodosActionPerformed

    private void rdFavoritosTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFavoritosTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdFavoritosTodosActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        // TODO add your handling code here:
        String jpql = "";
        if (rdDisponivelSim.isSelected()) {
            if (rdFavoritosSim.isSelected()) {
                jpql = "SELECT m FROM Imovel m WHERE m.favorite = TRUE AND m.cliente = NULL";
            } else if (rdFavoritosNao.isSelected()) {
                jpql = "SELECT m FROM Imovel m WHERE m.favorite = FALSE AND m.cliente = NULL";
            } else {
                jpql = "SELECT m FROM Imovel m WHERE m.cliente = NULL";
            }

        } else if (rdDisponivelNao.isSelected()) {
            if (rdFavoritosSim.isSelected()) {
                jpql = "SELECT m FROM Imovel m WHERE m.favorite = TRUE AND m.cliente != NULL";
            } else if (rdFavoritosNao.isSelected()) {
                jpql = "SELECT m FROM Imovel m WHERE m.favorite = FALSE AND m.cliente != NULL";
            } else {
                jpql = "SELECT m FROM Imovel m WHERE m.cliente != NULL";
            }
        } else {
            if (rdFavoritosSim.isSelected()) {
                jpql = "SELECT m FROM Imovel m WHERE m.favorite = TRUE";
            } else if (rdFavoritosNao.isSelected()) {
                jpql = "SELECT m FROM Imovel m WHERE m.favorite = FALSE";
            } else {
                jpql = "SELECT m FROM Imovel m";
            }
        }
        
        TypedQuery<Imovel> query = Main.em.createQuery(jpql, Imovel.class);
        List<Imovel> thisList = query.getResultList();
        System.out.println(thisList);
        
        try {
            this.setVisible(false);
            Report.createReport(thisList, "ImoveisDisponiveis.jrxml");
            this.dispose();
        } catch (JRException ex) {
            Logger.getLogger(ReportJDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ReportJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReportJDialog dialog = new ReportJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.ButtonGroup btnGroupDisponivel;
    private javax.swing.ButtonGroup btnGroupFavorito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdDisponivelNao;
    private javax.swing.JRadioButton rdDisponivelSim;
    private javax.swing.JRadioButton rdDisponivelTodos;
    private javax.swing.JRadioButton rdFavoritosNao;
    private javax.swing.JRadioButton rdFavoritosSim;
    private javax.swing.JRadioButton rdFavoritosTodos;
    // End of variables declaration//GEN-END:variables
}
