/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.imobi.view;

import br.com.imobi.app.Main;
import br.com.imobi.model.Cliente;
import br.com.imobi.model.Imovel;
import java.util.List;
import javax.persistence.TypedQuery;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dglsw
 */
public class ClientesJFrame extends javax.swing.JInternalFrame {
    private final String[] columns = {"Código", "Nome", "CPF", "Telefone"};
    private DefaultTableModel dtm;

    /**
     * Creates new form NotificacoesJFrame
     */
    public ClientesJFrame() {
        initComponents();
        initState();
    }
    
    private void initState(){
        dtm = new DefaultTableModel(columns, 0);
        tblClientes.setModel(dtm);
        tblClientes.setDefaultEditor(Cliente.class, null);
        updateTable();
    }
    
    public void updateTable(){
        //Limpar tabela
        while(tblClientes.getRowCount()>0){
            dtm.removeRow(0);
        }
        
        //setar títulos
        dtm = new DefaultTableModel(columns, 0);
        
        String jpql = "SELECT m FROM Cliente m";
        TypedQuery<Cliente> query = Main.em.createQuery(jpql, Cliente.class);
        List<Cliente> thisList = query.getResultList();
        
        //add linhas
        for (Cliente m : thisList) {
            String[] row = {String.valueOf(m.getId()), m.getNome(), m.getCpf(), m.getTelefone()};
            dtm.addRow(row);
        }
        tblClientes.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Clientes");
        setVisible(true);

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Descrição", "Imóvel", "Data", "Hora"
            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        setBounds(0, 0, 903, 481);
    }// </editor-fold>//GEN-END:initComponents

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        if(tblClientes.getSelectedRow() != -1){
            String id = (String)dtm.getValueAt(tblClientes.getSelectedRow(), 0);
            
            String jpql = "SELECT c FROM Cliente c WHERE c.id = :id";
            TypedQuery<Cliente> query = Main.em.createQuery(jpql, Cliente.class);
            query.setParameter("id", Integer.valueOf(id));
            Cliente cliente = query.getSingleResult();
            HomeJFrame.selectedCliente = cliente;
           
        }
    }//GEN-LAST:event_tblClientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
