/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.imobi.view;

import br.com.imobi.app.Main;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author dglsw
 */
public class HomeJFrame extends javax.swing.JFrame {

    private final ImoveisJFrame janelaImoveis = new ImoveisJFrame();
    private final FavoritosJFrame janelaFavoritos = new FavoritosJFrame();
    private final MensagensJFrame janelaMensagens = new MensagensJFrame();
    private final NotificacoesJFrame janelaNotificacoes = new NotificacoesJFrame();
    private final ClientesJFrame janelaClientes = new ClientesJFrame();

    private int selectedIndex = 0;

    /**
     * Creates new form Home
     */
    public HomeJFrame() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        dskMain = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnNotificacoes = new javax.swing.JButton();
        btnMensagens = new javax.swing.JButton();
        btnFavoritos = new javax.swing.JButton();
        btnImoveis = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setExtendedState(6);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnVoltar.setText("Novo");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dskMainLayout = new javax.swing.GroupLayout(dskMain);
        dskMain.setLayout(dskMainLayout);
        dskMainLayout.setHorizontalGroup(
            dskMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dskMainLayout.setVerticalGroup(
            dskMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/code_icon.png"))); // NOI18N

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);
        jToolBar1.setAutoscrolls(true);

        btnNotificacoes.setText("Notificações");
        btnNotificacoes.setFocusable(false);
        btnNotificacoes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNotificacoes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNotificacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificacoesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNotificacoes);

        btnMensagens.setText("Mensagens");
        btnMensagens.setFocusable(false);
        btnMensagens.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMensagens.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMensagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMensagensActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMensagens);

        btnFavoritos.setText("Favoritos");
        btnFavoritos.setFocusable(false);
        btnFavoritos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFavoritos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFavoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavoritosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFavoritos);

        btnImoveis.setText("Imóveis");
        btnImoveis.setFocusable(false);
        btnImoveis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImoveis.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImoveisActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImoveis);

        btnClientes.setText("Clientes");
        btnClientes.setFocusable(false);
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 951, Short.MAX_VALUE)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir))
                    .addComponent(dskMain))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnSalvar)
                    .addComponent(btnVoltar))
                .addGap(27, 27, 27)
                .addComponent(dskMain)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        setSize(new java.awt.Dimension(1359, 730));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        selectedIndex = 4;
        janelaClientes.setVisible(true);

        try {
            janelaClientes.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(HomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        dskMain.add(janelaClientes);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnMensagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensagensActionPerformed
        // TODO add your handling code here:
        selectedIndex = 1;
        janelaMensagens.setVisible(true);
        try {
            janelaMensagens.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(HomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        dskMain.add(janelaMensagens);
    }//GEN-LAST:event_btnMensagensActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNotificacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificacoesActionPerformed
        // TODO add your handling code here:
        selectedIndex = 0;
        janelaNotificacoes.setVisible(true);
        try {
            janelaNotificacoes.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(HomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        dskMain.add(janelaNotificacoes);

    }//GEN-LAST:event_btnNotificacoesActionPerformed

    private void btnFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoritosActionPerformed
        // TODO add your handling code here:
        selectedIndex = 2;
        janelaFavoritos.setVisible(true);
        try {
            janelaFavoritos.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(HomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        dskMain.add(janelaFavoritos);
    }//GEN-LAST:event_btnFavoritosActionPerformed

    private void btnImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImoveisActionPerformed
        // TODO add your handling code here:
        selectedIndex = 3;
        janelaImoveis.setVisible(true);
        try {
            janelaImoveis.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(HomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        dskMain.add(janelaImoveis);
    }//GEN-LAST:event_btnImoveisActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        switch (selectedIndex) {
            case 0:
                System.out.println("br.com.imobi.view.HomeJFrame.btnVoltarActionPerformed()");
                break;
            case 1:
                NovaMensagemJDialog dialog = new NovaMensagemJDialog(this, rootPaneCheckingEnabled);
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
                break;
            case 2:
                System.out.println("br.com.imobi.view.HomeJFrame.btnVoltarActionPerformed()");
                break;
            case 3:
                System.out.println("br.com.imobi.view.HomeJFrame.btnVoltarActionPerformed()");
                break;
            case 4:
                System.out.println("br.com.imobi.view.HomeJFrame.btnVoltarActionPerformed()");
                break;
            default:
                JOptionPane.showMessageDialog(this, "Erro: Opção de seleção inválida");

        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        try {
            Main.closeConn();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFavoritos;
    private javax.swing.JButton btnImoveis;
    private javax.swing.JButton btnMensagens;
    private javax.swing.JButton btnNotificacoes;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JDesktopPane dskMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
