/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.imobi.view;

import br.com.imobi.app.Main;
import br.com.imobi.app.Util;
import br.com.imobi.model.Cliente;
import br.com.imobi.model.Imovel;
import br.com.imobi.report.ReportJDialog;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author dglsw
 */
public class HomeJFrame extends javax.swing.JFrame {
    
    public static ImoveisJFrame janelaImoveis;
    public static FavoritosJFrame janelaFavoritos;
    public static NotificacoesJFrame janelaNotificacoes;
    public static MensagensJFrame janelaMensagens;
    public static ClientesJFrame janelaClientes;
    
    private int selectedIndex = -1;
    public static Imovel selectedImovel;
    public static Cliente selectedCliente;

    /**
     * Creates new form Home
     */
    public HomeJFrame() {
        initComponents();
        initState();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }
    
    private void initState() {
        lblUsuario.setText("Olá "+Main.uLogado.getName());
        if (!Main.uLogado.isAdmin()) {
            Util.print("is Not admin");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        dskMain = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnNotificacoes = new javax.swing.JButton();
        btnMensagens = new javax.swing.JButton();
        btnFavoritos = new javax.swing.JButton();
        btnImoveis = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        btnGerarRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setExtendedState(6);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dskMainLayout = new javax.swing.GroupLayout(dskMain);
        dskMain.setLayout(dskMainLayout);
        dskMainLayout.setHorizontalGroup(
            dskMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dskMainLayout.setVerticalGroup(
            dskMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/code_icon.png"))); // NOI18N

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);
        jToolBar1.setAutoscrolls(true);

        btnNotificacoes.setText("Notificações");
        btnNotificacoes.setFocusable(false);
        btnNotificacoes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNotificacoes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNotificacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificacoesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNotificacoes);

        btnMensagens.setText("Mensagens");
        btnMensagens.setFocusable(false);
        btnMensagens.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMensagens.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMensagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMensagensActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMensagens);

        btnFavoritos.setText("Favoritos");
        btnFavoritos.setFocusable(false);
        btnFavoritos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFavoritos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFavoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavoritosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFavoritos);

        btnImoveis.setText("Imóveis");
        btnImoveis.setFocusable(false);
        btnImoveis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImoveis.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImoveisActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImoveis);

        btnClientes.setText("Clientes");
        btnClientes.setFocusable(false);
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClientes);

        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblUsuario.setText("jLabel3");

        btnGerarRelatorio.setText("Relatório");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAbrir)
                        .addGap(355, 355, 355)
                        .addComponent(lblUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 447, Short.MAX_VALUE)
                        .addComponent(btnGerarRelatorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir))
                    .addComponent(dskMain))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnNovo)
                    .addComponent(btnAbrir)
                    .addComponent(lblUsuario)
                    .addComponent(btnGerarRelatorio))
                .addGap(27, 27, 27)
                .addComponent(dskMain)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        setSize(new java.awt.Dimension(1359, 730));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        //if (selectedIndex != 4) {
            selectedIndex = 4;
            btnNovo.setEnabled(true);
            btnExcluir.setEnabled(true);
            btnGerarRelatorio.setEnabled(false);
            
            if (janelaClientes == null) {
                janelaClientes = new ClientesJFrame();
                dskMain.add(janelaClientes);
            }
            if (!janelaClientes.isVisible()) {
                janelaClientes.setVisible(true);
            }
            
            janelaClientes.toFront();
            janelaClientes.setFocusable(true);
            try {
                janelaClientes.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(HomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        //}

    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnMensagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensagensActionPerformed
        if (selectedIndex != 1) {
            selectedIndex = 1;
            btnNovo.setEnabled(true);
            btnAbrir.setEnabled(false);
            btnExcluir.setEnabled(true);
            btnGerarRelatorio.setEnabled(false);
            if (janelaMensagens == null) {
                janelaMensagens = new MensagensJFrame();
                dskMain.add(janelaMensagens);
            }
            if (!janelaMensagens.isVisible()) {
                janelaMensagens.setVisible(true);
            }
            
            janelaMensagens.toFront();
            try {
                janelaMensagens.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(HomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }

    }//GEN-LAST:event_btnMensagensActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Util.print("Excluir");
        switch (selectedIndex) {
            case 0:
                System.out.println("0");
                break;
            case 1:
                System.out.println("1");
                break;
            
            case 2:
                System.out.println("2");
                break;
            case 3:
                Imovel u = Main.em.find(Imovel.class, selectedImovel.getId());
                
                if (u != null) {
                    try {
                        Main.em.getTransaction().begin();
                        Main.em.remove(u);
                        Main.em.getTransaction().commit();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(rootPane, "Houve um erro ao tentar excluir o imóvel!");
                    }
                    janelaImoveis.updateTable();
                }
                break;
            case 4:
                Cliente c = Main.em.find(Cliente.class, selectedCliente.getId());
                
                if (c != null) {
                    try {
                        Main.em.getTransaction().begin();
                        Main.em.remove(c);
                        Main.em.getTransaction().commit();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(rootPane, "Houve um erro ao tentar excluir o imóvel!");
                    }
                    janelaClientes.updateTable();
                }
                break;
            default:
                JOptionPane.showMessageDialog(this, "Erro: Opção de seleção inválida");
            
        }
        

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNotificacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificacoesActionPerformed
        // TODO add your handling code here:
        if (selectedIndex != 0) {
            selectedIndex = 0;
            btnNovo.setEnabled(false);
            btnAbrir.setEnabled(false);
            btnExcluir.setEnabled(true);
            btnGerarRelatorio.setEnabled(false);
            if (janelaNotificacoes == null) {
                janelaNotificacoes = new NotificacoesJFrame();
                dskMain.add(janelaNotificacoes);
            }
            if (!janelaNotificacoes.isVisible()) {
                janelaNotificacoes.setVisible(true);
            }
            
            janelaNotificacoes.toFront();
            try {
                janelaNotificacoes.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(HomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        

    }//GEN-LAST:event_btnNotificacoesActionPerformed

    private void btnFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoritosActionPerformed
        // TODO add your handling code here:
        if (selectedIndex != 2) {
            selectedIndex = 2;
            btnNovo.setEnabled(false);
            btnAbrir.setEnabled(true);
            btnExcluir.setEnabled(false);
            btnGerarRelatorio.setEnabled(false);
            if (janelaFavoritos == null) {
                janelaFavoritos = new FavoritosJFrame();
                dskMain.add(janelaFavoritos);
            }
            if (!janelaFavoritos.isVisible()) {
                janelaFavoritos.setVisible(true);
            }
            janelaFavoritos.toFront();
            
            try {
                janelaFavoritos.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(HomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnFavoritosActionPerformed

    private void btnImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImoveisActionPerformed
        // TODO add your handling code here:
        if (selectedIndex != 3) {
            btnNovo.setEnabled(true);
            btnNovo.setEnabled(true);
            btnGerarRelatorio.setEnabled(true);
            selectedIndex = 3;
            
            btnAbrir.setEnabled(true);
            if (janelaImoveis == null) {
                janelaImoveis = new ImoveisJFrame();
                dskMain.add(janelaImoveis);
            }
            if (!janelaImoveis.isVisible()) {
                janelaImoveis.setVisible(true);
            }
            janelaImoveis.toFront();
            
            try {
                janelaImoveis.setMaximum(true);
                
            } catch (PropertyVetoException ex) {
                Logger.getLogger(HomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnImoveisActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        switch (selectedIndex) {
            case 0:
                System.out.println("br.com.imobi.view.HomeJFrame.btnVoltarActionPerformed()");
                break;
            case 1:
                MensagemJDialog mensagemDialog = new MensagemJDialog(this, rootPaneCheckingEnabled);
                mensagemDialog.setLocationRelativeTo(null);
                mensagemDialog.setVisible(true);
                break;
            
            case 2:
                System.out.println("br.com.imobi.view.HomeJFrame.btnVoltarActionPerformed()");
                break;
            case 3:
                ImoveisJDialog imoveisDialog = new ImoveisJDialog(this, rootPaneCheckingEnabled);
                imoveisDialog.setLocationRelativeTo(null);
                imoveisDialog.setVisible(true);
                break;
            case 4:
                ClientesJDialog clientesDialog = new ClientesJDialog(this, rootPaneCheckingEnabled);
                clientesDialog.setLocationRelativeTo(null);
                clientesDialog.setVisible(true);
                System.out.println("br.com.imobi.view.HomeJFrame.btnVoltarActionPerformed()");
                break;
            default:
                JOptionPane.showMessageDialog(this, "Erro: Opção de seleção inválida");
            
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        try {
            Main.closeConn();
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_formWindowClosed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        Util.print("Abrir");
        switch (selectedIndex) {
            case 0:
                System.out.println("0");
                break;
            case 1:
                MensagemJDialog mensagemDialog = new MensagemJDialog(this, rootPaneCheckingEnabled);
                mensagemDialog.setLocationRelativeTo(null);
                mensagemDialog.setVisible(true);
                break;
            
            case 2:
                System.out.println("2");
                ImoveisJDialog favoritoDialog = new ImoveisJDialog(this, rootPaneCheckingEnabled, selectedImovel);
                favoritoDialog.setLocationRelativeTo(null);
                favoritoDialog.setVisible(true);
                break;
            case 3:
                ImoveisJDialog imoveisDialog = new ImoveisJDialog(this, rootPaneCheckingEnabled, selectedImovel);
                imoveisDialog.setLocationRelativeTo(null);
                imoveisDialog.setVisible(true);
                break;
            case 4:
                ClientesJDialog clientesDialog = new ClientesJDialog(this, rootPaneCheckingEnabled, selectedCliente);
                clientesDialog.setLocationRelativeTo(null);
                clientesDialog.setVisible(true);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Erro: Opção de seleção inválida");
            
        }

    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed
        // TODO add your handling code here:
        ReportJDialog reportDialog = new ReportJDialog(this, true);
        reportDialog.setLocationRelativeTo(null);
        reportDialog.setVisible(true);
    }//GEN-LAST:event_btnGerarRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFavoritos;
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.JButton btnImoveis;
    private javax.swing.JButton btnMensagens;
    private javax.swing.JButton btnNotificacoes;
    private javax.swing.JButton btnNovo;
    private javax.swing.JDesktopPane dskMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables

}
